### ISSUE TITLE
Entrega desafio 1 -  Maratona Full Cycle 2.0

### ISSUE THREAD

**Issue by anderson-scherer** [codeedu/maratona2-plataforma-lives#1]
Imagem docker com server em node.js

https://hub.docker.com/r/andersonscherer/nodejs-alpine

**Comment by argentinaluiz** [comment]
Olá Anderson, tudo bem?

Obrigado por compartilhar vamos corrigir!! Consegue acrescentar lá nos comentários? Assim controlamos melhor!!

;)
