### ISSUE TITLE
não roda no Windows10

### ISSUE THREAD

**Issue by bmnds** [codeedu/maratona2-plataforma-lives#2]
Ao tentar rodar o `docker-compose up` no Windows10, percebi que o `entrypoint.sh` não é executado, tanto pelo _frontend_ quanto pelo _backend_ .

*Nota: eu executei a conversão informada no README:
```
$ dos2unix ./frontend/.docker/entrypoint.sh
dos2unix: converting file ./frontend/.docker/entrypoint.sh to Unix format...

$ dos2unix ./backend/.docker/entrypoint.sh
dos2unix: converting file ./backend/.docker/entrypoint.sh to Unix format...

```

Essa é a versão do Docker que estou utilizando:
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by argentinaluiz** [comment]
Oi @bmnds 

Acredito que esteja rodando o Docker Toolbox.

Rode o comando no terminal:
```git config --global core.autocrlf=input```

Exclua o projeto que você baixou e baixe-o com o comando git clone.

Tente subir o projeto novamente.

**Comment by bmnds** [comment]
o Docker Toolbox é antigo, no Win10 Pro é o Docker Desktop que já roda direto sobre o Hyper-V.

Fiz o procedimento e mesmo assim não funcionou. Excluí o repositório, os containers e as imagens pra gerar tudo do zero.

**Comment by bmnds** [comment]
O problema agora é esse:
```
micro-live-manager-backend | [Nest] 85   - 05/06/2020, 7:26:22 PM   [ExceptionHandler] ER_HOST_NOT_PRIVILEGED: Host '172.30.0.4' is not allowed to connect to this MySQL server +2ms
micro-live-manager-backend | Error: ER_HOST_NOT_PRIVILEGED: Host '172.30.0.4' is not allowed to connect to this MySQL server
```

**Comment by argentinaluiz** [comment]
Olá @bmnds ,

Apague a pasta backend/.docker/dbdata, onde se encontra o banco de dados, ao rodar um docker-compose up vai criar novamente.

**Comment by bmnds** [comment]
@argentinaluiz , esqueci de voltar aqui pra dar o feedback, mas para resolver o erro `ER_HOST_NOT_PRIVILEGED` do mysql eu precisei usar um volume compartilhado no `docker-compose.yaml`:
```yaml
#mysql
  db:
    volumes:
#      - ./backend/.docker/dbdata:/var/lib/mysql
      - db_data:/var/lib/mysql

# redis
  redis:
    volumes:
#      - ./backend/.docker/redisdata:/data
      - cache_data:/data

volumes:
  db_data:
  cache_data:
```

**Comment by argentinaluiz** [comment]
Olá @argentinaluiz ,

Ótimo! Normalmente isto é usando para PostgreSQL por conta do compartilhamento, mas o MySQL funciona.

Acredito que deva ser a versão do Docker ou outra coisa no Windows.
