### ISSUE TITLE
Não é possível conectar ao micro-live-manager_backend

### ISSUE THREAD

**Issue by adrianokerber** [codeedu/maratona2-plataforma-lives#3]
Baixei o repositório e rodei a aplicação usando o comando `docker-compose up`. Consegui acessar a página do frontend `http://localhost:3001/` mas quando tentei conectar ao `micro-live-manager_backend` ele nunca responde. Tentei acessar via frontend, depois tentei direto via browser e via Postman pela rota: `http://localhost:3000` ou `http://localhost:3000/lives` e nenhuma das formas funcionou. Alguma ideia de porque?

Todos os containers estão rodando e sem erros, mas não consigo acessar o backend...

System configs:
* Docker Desktop
* Windows 10 Education

**Comment by argentinaluiz** [comment]
Olá @adrianokerber , verifique os logs no terminal, mas se acessar http://localhost:3000 deve mostrar Hello World.

Verifique se os .env estão gerados tanto em frontend quanto em backend. 

Aproveite e faça um git pull origin master para pegar uma nova atualização no código-fonte (não esqueça de recopiar o .env.example para o .env

**Comment by adrianokerber** [comment]
@argentinaluiz não havia notado erros no terminal antes, mas rodei novamente e percebi este:
```console
micro-live-manager-backend | internal/modules/cjs/loader.js:1025
micro-live-manager-backend |   return process.dlopen(module, path.toNamespacedPath(filename));
micro-live-manager-backend |                  ^
micro-live-manager-backend |
micro-live-manager-backend | Error: Error loading shared library /home/node/app/backend/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: Exec format error
```

Os `.env` foram criados da forma correta e o código está atualizado com o repositório. Acredito que o problema seja com a dependência do bcrypt como mostra no erro, só não entendo o porquê. Alguma ideia do que possa estar acontecendo?

Nota: Estou com o Node v12.16.3

**Comment by argentinaluiz** [comment]
Olá @adrianokerber ,

A princípio, acredito que a instalação das dependências não ocorreu com sucesso, remova a pasta node_modules da pasta backend e suba novamente os containers do microsserviço, a instalação será feita novamente.

;)

**Comment by adrianokerber** [comment]
Fiz o sugerido @argentinaluiz mas não obtive sucesso. Agora tenho os seguintes erros:
```console
micro-live-manager-backend |
micro-live-manager-backend | node_modules/@nestjs/microservices/index.d.ts:11:15 - error TS2307: Cannot find module './server'.
micro-live-manager-backend |
micro-live-manager-backend | 11 export * from './server';
micro-live-manager-backend |                  ~~~~~~~~~~
micro-live-manager-backend |
micro-live-manager-backend | node_modules/@nestjs/microservices/interfaces/microservice-configuration.interface.d.ts:4:24 - error TS2307: Cannot find module '../server/server'.
micro-live-manager-backend | 
micro-live-manager-backend | 4 import { Server } from '../server/server';
micro-live-manager-backend |                          ~~~~~~~~~~~~~~~~~~
micro-live-manager-backend |
micro-live-manager-backend | [12:15:27 PM] Found 2 errors. Watching for file changes.
```

Minha versão do Nestjs é 7.1.5

**Comment by argentinaluiz** [comment]
Olá @adrianokerber ,

Parece que a instalação não aconteceu com sucesso, uma possível causa é falta de disco liberado para o Docker.

Verifique esta janela nas configurações do Docker: http://prntscr.com/sdcu8p.

Se verifique que está cheio ou praticamente cheio, libere mais um pouco de espaço de disco, ou exclua todas as imagens e Docker e tente levantar tudo novamente.

;)

**Comment by adrianokerber** [comment]
Olá @argentinaluiz,

Tenho 64GB como tamanho de imagem mas só usei 1.5GB.

Também já tentei remover as imagens e criar novamente, mas sempre ocorre o mesmo erro...
